kotlin.code.style=official

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=1.1.1
mod.group=net.cdnbcn
mod.id=simple_block_breaker
mod.name=Simple Block Breaker

publish.modrinth=UoOs7wz1
publish.curseforge=1227573
