deps.neoforge=21.1.215
deps.kotlin_for_forge=5.11.0
deps.parchment_mapping=2024.11.17

# Minecraft dependency for neoforge.mods.toml
mod.mc_dep=[1.21.1]

# Release title for Modrinth and Curseforge
mod.mc_title=1.21.1

# Space-separated compatible versions for publishing
mod.mc_targets=1.21.1

modrinth.kotlin_for_forge.id=ordsPcFz
modrinth.kotlin_for_forge.version=NrSebcsG
curseforge.kotlin_for_forge.slug=kotlin-for-forge